##baseURL = "https://vegvesen.github.io/nap-help/"
baseURL = "https://transportportal.atlas.vegvesen.no"
relativeURLs = "true"
languageCode = "no"
defaultContentLanguage = "no"
defaultContentLanguageInSubdir = true
buildDrafts = false
enableEmoji = true
enableGitInfo = true
EnableMissingTranslationPlaceholders = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "silhouette-hugo"
publishDir = "docs"
imggroup = "sorfold"
fractions = "false"

[frontmatter]
  lastmod = [":fileModTime", ":default"]

[languages]
  [languages.no]
   datacat = "https://data.transportportal.no/datasets"
   datacatText = "Datakatalog"
   contentDir = "content/no"
   title = "transportportal.no"
   weight = 1

  [languages.en]
    datacat = "https://data.transportportal.no/datasets/?lang=en"
    datacatText = "Data Catalog"
    title = "transportportal.no"
    contentDir = "content/en"
    weight = 2


[params]
  author = "Statens vegvesen"
  introDescription = "Intro"
  contactEmail = "kontakt@transportportal.no"
  [params.img]
     imgauthor = "Jon Opseth, Statens vegvesen"
     background_image = "images/NAP-forside-ny.jpg"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
