#!/bin/bash

FILE=$1
GROUP="vt/transportportal"
ARTIFACT="napt"
# Keyfile not part of repo, needs to be generated by JFrog for personal use
KEY=`cat .artrepo.key`

echo "Uploading $FILE to artrepo ..."
curl -H X-JFrog-Art-Api:${KEY} -T ${FILE} https://artrepo.vegvesen.no/artifactory/webcontent-release-local/${GROUP}/${ARTIFACT}/
