#!/bin/bash

# Usage: artrepo.sh <artefact file>

source env.sh

FILE=$1

if [ ! -f "$FILE" ]; then
    echo "Artefact $FILE not found?"
    exit
fi
# Artrepo group uses slashes as sep, Atlas/Maven uses "dot"
GROUP=`echo $GROUP_ID | sed 's/\./\//'`

# Artrepo keyfile (NB! not part of our GIT repo) needs to be generated by Artifactory for personal use
KEY=`cat $ARTREPO_KEYFILE`

echo "Uploading artefact $FILE to Artifactory repo ${ARTREPO_REPO}, group $GROUP, artefact $ARTIFACT_ID ..."

curl -H X-JFrog-Art-Api:${KEY} -T ${FILE} https://artrepo.vegvesen.no/artifactory/${ARTREPO_REPO}/${GROUP}/${ARTIFACT_ID}/
