#!/bin/bash

# Common env settings

# Hugo binary
HUGO="/C/Data/Hugo/bin/hugo.exe"
# Hugo root
HUGO_ROOT="/C/Data/Hugo/sites/nap-help"
# Hugo docroot relative to project root
HUGO_DOCS="docs"
# Atlas config relative to project docroot
ATLAS_CONFIG="atlas"
# IKT-løsning
IKT="napt"
# ac binary
AC="/C/Programfiler/Atlas/bin/ac.exe"
# Atlas API
API="https://atlas-api.atlas.vegvesen.no/api"
# Buildtype - webcontent|java|dotnetcore
BUILD_TYPE="webcontent"
# Packet type - depends on build type ..
PACKET_TYPE="tar.gz"
# Group in arttifact repo
GROUP_ID="vt.transportportal"
# artifactId in artifact repo
ARTIFACT_ID="napt"
# Deployment prefix - deployments will be named $DPL-PREFIX-color
# where color = blue or green
DPL_PREFIX="transport"
# Keyfile with personal token generated by Artifactory
ARTREPO_KEYFILE=".artrepo.key"
# Repo
ARTREPO_REPO="webcontent-release-local"
# Atlas dispatcher 
DISPATCHER="napt-dispatcher"

function fortsett(){
  prompt="$1 - continue? [yn] ";
  read -p "$prompt" svar
  case $svar in
   [Yy])

   ;;
   [nN])
      exit
       ;;

    *)

  esac

};
